# The overall template of the release notes
template: |
  Compatible with OpenSearch (**set version here**).
  $CHANGES

# Setting the formatting and sorting for the release notes body
name-template: Version (set version here)
change-template: '* $TITLE (#$NUMBER)'
sort-by: merged_at
sort-direction: ascending
replacers:
  - search: '##'
    replace: '###'

# Organizing the tagged PRs into categories
categories:
  - title: 'Breaking Changes'
    labels:
      - 'Breaking Changes'
  - title: 'Security'
    labels:
      - 'Security'
      - 'security fix'
      - 'security vulnerability'
  - title: 'Features'
    labels:
      - 'Features'
  - title: 'Enhancements'
    labels:
      - 'Enhancements'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'Bug Fixes'
      - 'bug'
  - title: 'Infrastructure'
    labels:
      - 'Infrastructure'
      - 'configuration error'
  - title: 'Documentation'
    labels:
      - 'Documentation'
      - 'documentation'
  - title: 'Maintenance'
    labels:
      - 'Maintenance'
      - 'meta'
      - 'release'
  - title: 'Refactoring'
    labels:
      - 'Refactoring'