# The overall template of the release notes
template: |
  Compatible with OpenSearch (**set version here**).
  $CHANGES

# Setting the formatting and sorting for the release notes body
name-template: Version (set version here)
change-template: '* $TITLE (#$NUMBER)'
sort-by: merged_at
sort-direction: ascending
replacers:
  - search: '##'
    replace: '###'

# Organizing the tagged PRs into categories
categories:
  - title: 'Breaking Changes'
    labels:
      - 'breaking'
  - title: 'Security'
    labels:
      - 'security fix'
  - title: 'Features'
    labels:
      - 'feature'
  - title: 'Enhancements'
    labels:
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'bug'
  - title: 'Infrastructure'
    labels:
      - 'infrastructure'
  - title: 'Documentation'
    labels:
      - 'documentation'
  - title: 'Maintenance'
    labels:
      - 'maintenance'
  - title: 'Refactoring'
    labels:
      - 'refactoring'