/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 */
package org.opensearch.search.relevance.ranker;

import org.opensearch.action.search.SearchRequest;
import org.opensearch.search.SearchHits;
import org.opensearch.search.relevance.preprocess.QueryParser.QueryParserResult;

public interface Ranker {

  /**
   * Decide whether the input request is eligible for re-ranking
   * @param request input request
   * @return boolean decision on whether to re-rank
   */
  boolean shouldRerank(final SearchRequest request);

  /**
   * Rank hits based on the provided query
   * @param hits hits to be re-ranked
   * @param queryParserResult query text and document field name to be used by the ranker
   * @return SearchHits ordered by score generated by ranker
   */
  SearchHits rank(final SearchHits hits, QueryParserResult queryParserResult);
}
