/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 */
package org.opensearch.search.relevance.transformer;

import org.opensearch.action.search.SearchRequest;
import org.opensearch.common.settings.Setting;
import org.opensearch.search.SearchHits;
import org.opensearch.search.relevance.configuration.ResultTransformerConfiguration;
import org.opensearch.search.relevance.configuration.ResultTransformerConfigurationFactory;

import java.util.List;

public interface ResultTransformer {
  /**
   * Get the list of settings supported by the transformer
   * @return list of transformer settings
   */
  List<Setting<?>> getTransformerSettings();

  /**
   * @return a factory able to construct configurations for this transformer.
   */
  ResultTransformerConfigurationFactory getConfigurationFactory();

  /**
   * Decide whether to apply the transformer on the input request
   * @param request input Search Request
   * @param configuration Configuration parameters for the transformer
   * @return boolean decision on whether to apply the transformer
   */
  boolean shouldTransform(final SearchRequest request, final ResultTransformerConfiguration configuration);

  /**
   * Preprocess the incoming Search Request to support the requirements of the transformer
   * @param request input Search Request
   * @param configuration Configuration parameters for the transformer
   * @return SearchRequest with updated attributes
   */
  SearchRequest preprocessRequest(final SearchRequest request,
      final ResultTransformerConfiguration configuration);

  /**
   * Rank hits based on the provided query
   * @param hits hits to be re-ranked
   * @param request Search request
   * @param configuration Configuration parameters for the transformer
   * @return SearchHits ordered by score generated by ranker
   */
  SearchHits transform(final SearchHits hits,
      final SearchRequest request,
      final ResultTransformerConfiguration configuration);
}
