name: Build & Test Search Request Processor
on:
  schedule:
    - cron: '0 0 * * *'  # every night
  push:
    branches:
      - "*"
      - "feature/**"
  pull_request:
    branches:
      - "*"
      - "feature/**"

jobs:
  Build-search-request-processor:
    strategy:
      matrix:
        java: [11, 17]
        os: [ubuntu-latest, macos-latest] # want to get the build running first; fixing windows build after- windows-latest]

    name: Build and Test Search Request Processor Plugin
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Search Request Processor
        uses: actions/checkout@v1

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Run build
        run: |
          ./gradlew build

      - name: Upload Coverage Report
        if: startsWith(matrix.os,'ubuntu')
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

#  Build-search-request-processor-Windows:
#    strategy:
#      matrix:
#        java: [ 11, 17 ]
#
#    name: Build and Test Search Request Processor Plugin on Windows
#    runs-on: windows-latest

#    steps:
#      - name: Checkout Search Request Processor
#        uses: actions/checkout@v1

#      - name: Setup Java ${{ matrix.java }}
#        uses: actions/setup-java@v1
#        with:
#          java-version: ${{ matrix.java }}
#
#      - name: Run build
#        run: |
#          ./gradlew.bat build

